# 1. Build
FROM node:14.19.1 as builder
WORKDIR /app
COPY package*.json ./
RUN  npm install
COPY . .
ENV REACT_APP_NAME=solarmon
ENV CHINESE_FOOD=good

EXPOSE 3000
# RUN npm run build
CMD ["npm", "start"]

# 2. Serve [production]
# FROM nginx:stable-alpine
# COPY --from=builder /app/build /usr/share/nginx/html
# COPY --from=builder /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf
# EXPOSE 3000
# CMD ["nginx", "-g", "daemon off;"]