# 1. Build
FROM node:14.19.1 as builder
WORKDIR /app

COPY package*.json ./
RUN  npm install
COPY . .
ARG REACT_APP_NAME
ENV REACT_APP_NAME=$REACT_APP_NAME
RUN npm run build

# 2. Serve [production]
FROM nginx
COPY --from=builder /app/build /usr/share/nginx/html
# COPY --from=builder /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf
# EXPOSE 3000
# CMD ["nginx", "-g", "daemon off;"]